sudo: required

language: python

env:
  global:
    - REDHAT_BUILDER_IMAGE=alectolytic/rpmbuilder REDHAT_OS_ARCH=x86_64 COPR_REPOSITORY=@zealdocs/zeal
  matrix:
    - PACKAGING=redhat OS_TYPE=fedora OS_DIST=fedora OS_VERSION=27
    - PACKAGING=redhat OS_TYPE=centos OS_DIST=epel OS_VERSION=7

services:
  - docker

install: true

script:
  - |
    [[ "${PACKAGING}" == "${PACKAGING}" ]] \
      && git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep redhat/zeal.spec > /dev/null 2>&1 \
      || { echo "This is not a Red Hat packaging change. Skipping build." && exit 0; }
    echo "Building Red Hat RPM ..."
    docker run -v ${PWD}/redhat:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${REDHAT_BUILDER_IMAGE}:${OS_TYPE}-${OS_VERSION}
    pip install copr-cli simplejson jinja2 argparse
    copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${REDHAT_OS_ARCH} "${COPR_REPOSITORY}" *.src.rpm
